version: "2"
services:

  web:
    image: gamer7569/nginx
    container_name: ${PROJECT_ID}-web
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}:/app
    links:
      - php

  php:
    image: gamer7569/php:latest
    #image: gamer7569/php:5.6
    container_name: ${PROJECT_ID}-php
    volumes:
      - ${PROJECT_ROOT}:/app
    links:
      - db
      - redis
      - mailhog

  db:
    image: gamer7569/mysql
    container_name: ${PROJECT_ID}-db
    ports:
      - "3306:3306"
    env_file: .env
    #volumes:
    #  - ${PROJECT_ROOT}/resources/mysql-dump:/docker-entrypoint-initdb.d  # Import .sql files
    #  - ${PROJECT_ROOT}/data/mysql-data:/var/lib/mysql                    # persistent database

  redis:
    image: redis:3-alpine
    container_name: ${PROJECT_ID}-redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: ${PROJECT_ID}-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
